title: "MuffinHunt Datapack"
theme: just-the-docs
color_scheme: "dark"
search_enabled: true
exclude: [README.md, crowdin.yml, renovate.json]
plugins:
  - "jekyll-github-metadata"
  - "jekyll-timeago"
  - "jekyll-paginate-v2"
  - "jekyll-mentions"
  - "jemoji"
url: https://osfanmuffin.github.io/muffinhunt-datapack-docs
domain: osfanmuffin.github.io
repository: osfanmuffin/muffinhunt-datapack-docs
