title: "MuffinHunt Datapack"
theme: just-the-docs
color_scheme: dark
search_enabled: false
exclude: [README.md, crowdin.yml, renovate.json, LICENSE.md, ]
plugins:
  - "jekyll-github-metadata"
  - "jekyll-timeago"
  - "jekyll-paginate-v2"
  - "jekyll-mentions"
  - "jemoji"
url: https://osfanbuff63.github.io/muffinhunt-datapack-docs
domain: osfanbuff63.github.io
repository: osfanbuff63/muffinhunt-datapack-docs
