name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - master 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup ruby
        uses: ruby/setup-ruby@2489e28c66b1217a91b825746a221cfd04965f67
        with:
          ruby-version: 3.1.2
      - name: Cache ruby dependencies
        uses: actions/cache@c3f1317a9e7b1ef106c153ac8c0f00fed3ddbc0d
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@e03ddfec9224b24ecf8a4607a31b53481485cf57
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: './'
          pre_build_commands: |
            git config --global user.name actions-user
            git config --global user.email action@github.com
      #- name: Init search
        #run: |
          #bundle config path vendor/bundle
          #bundle install
          #bundle exec just-the-docs rake search:init  
