name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - master 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            geo.mirror.pkgbuild.com:443
            github.com:443
            gk2hacprodeus1file7.blob.core.windows.net:443
            index.rubygems.org:443
            rubygems.org:443
      - name: Checkout repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup ruby
        uses: ruby/setup-ruby@09c10210cc6e998d842ce8433cd9d245933cd797
        with:
          ruby-version: 3.1.2
      - name: Cache ruby dependencies
        uses: actions/cache@a7c34adf76222e77931dedbf4a45b2e4648ced19
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@ed1f2e86643db8abe29378dd0a86462a84ec50c2
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: './'
          pre_build_commands: |
            git config --global user.name actions-user
            git config --global user.email action@github.com
